apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zhxity0p6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/zhxity0p6-java-springboot-gitops